image: buildpack-deps:stable-scm

variables:
  NJOBS: "2"

cache:
  paths:
    - opam-cache

before_script:
  - export HOME=$(pwd)
  - export EXTRA_OPAM="ocamlbuild" # some packages build extracted code this way
  - apt-get update -qy
  - apt-get install unzip libgtksourceview2.0-dev libgtksourceview-3.0-dev libncurses5-dev curl jq ruby bubblewrap -y
  - test -e ${HOME}/opam-cache/cache-${COMPILER}.tgz || scripts/opam-coq-init
  - curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh > install.sh
  - echo | sh install.sh
  - set -o pipefail

.opam-lint:
  script:
    - scripts/opam-coq-list-pr-files | xargs scripts/opam-coq-lint

.opam-build:
  script: |
    PR=${CI_BUILD_REF_NAME##pr-};
    echo "Github PR number: $PR";
    SKIP=$(set +o pipefail; curl https://api.github.com/repos/coq/opam-coq-archive/issues/$PR | jq -rc .body | grep ^ci-skip: | cat );
    echo "SKIP packages per user request: $SKIP";
    scripts/opam-coq-list-pr-files | xargs scripts/opam-coq-install-remove ${HOME}/opam-cache/cache-${COMPILER}.tgz $SKIP --
  artifacts:
    name: "$CI_JOB_NAME"
    when: on_failure
    paths:
      - log/
    expire_in: 1 week

    
opam-lint:4.02.3:
  extends: .opam-lint
  variables:
    COMPILER: "4.02.3"

opam-lint:4.05.0:
  extends: .opam-lint
  variables:
    COMPILER: "4.05.0"

opam-lint:4.07.1:
  extends: .opam-lint
  variables:
    COMPILER: "4.07.1"


opam-build:4.02.3:
  extends: .opam-build
  variables:
    COMPILER: "4.02.3"
  except:
    - web

opam-build:4.05.0:
  extends: .opam-build
  variables:
    COMPILER: "4.05.0"
  except:
    - web

opam-build:4.07.1:
  extends: .opam-build
  variables:
    COMPILER: "4.07.1"
  except:
    - web


opam-build-no-timeout:4.02.3:
  extends: .opam-build
  variables:
    COMPILER: "4.02.3"
  only:
    - web
  tags:
    - no-timeout

opam-build-no-timeout:4.05.0:
  extends: .opam-build
  variables:
    COMPILER: "4.05.0"
  only:
    - web
  tags:
    - no-timeout

opam-build-no-timeout:4.07.1:
  extends: .opam-build
  variables:
    COMPILER: "4.07.1"
  only:
    - web
  tags:
    - no-timeout
