variables:
  TRAVIS_BRANCH: "master"
  NJOBS: "2"

cache:
  paths:
    - opam-cache

before_script:
  - export TRAVIS_COMMIT="$CI_COMMIT_SHA"
  - export HOME=$(pwd)
  - apt-get update -qy
  - apt-get install unzip libgtksourceview2.0-dev -y
  - test -e ${HOME}/opam-cache/cache-${COMPILER}.tgz || scripts/opam-coq-init
  - curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh > install.sh
  - echo | sh install.sh
  - set -o pipefail

.opam-lint:
  script:
    - scripts/opam-coq-list-pr-files | xargs scripts/opam-coq-lint

.opam-build:
  script:
    - scripts/opam-coq-list-pr-files | xargs scripts/opam-coq-install-remove ${HOME}/opam-cache/cache-${COMPILER}.tgz

opam-lint:4.02.3:
  extends: .opam-lint
  variables:
    COMPILER: "4.02.3"

opam-lint:4.06.0:
  extends: .opam-lint
  variables:
    COMPILER: "4.06.0"

opam-build:4.02.3:
  extends: .opam-build
  variables:
    COMPILER: "4.02.3"

opam-build:4.06.0:
  extends: .opam-build
  variables:
    COMPILER: "4.06.0"
