language: c
env:
  global:
  - NJOBS=2
  - COMPILER_MIN="4.02.3"
  - COMPILER_MAX="4.06.0"

cache:
  apt: true
  directories:
  - ${HOME}/opam-cache

install:
- test -e ${HOME}/opam-cache/cache-${COMPILER}.tgz || scripts/opam-coq-init

script:
- set -o pipefail
- scripts/opam-coq-list-pr-files | xargs scripts/opam-coq-lint
- scripts/opam-coq-list-pr-files | xargs scripts/opam-coq-install-remove ${HOME}/opam-cache/cache-${COMPILER}.tgz
        
dist: trusty
sudo: required
matrix:
  include:
  - os: linux
    env:
      - COMPILER=${COMPILER_MIN}
    addons:
      apt:
        sources:
        - avsm
        packages:
        - opam
        - aspcud
        - gcc-multilib
        - libgtksourceview2.0-dev
  - os: linux
    env:
        - COMPILER=${COMPILER_MAX}
    addons:
      apt:
        sources:
        - avsm
        packages:
        - opam
        - aspcud
        - gcc-multilib
        - libgtksourceview2.0-dev
  - os: osx
    env:
      - COMPILER=${COMPILER_MAX}
    osx_image: xcode7.3
    before_install:
    - brew update
    - brew install opam
    
