language: c
env:
  global:
  - NJOBS=2
  matrix:
  - COMPILER="4.02.3"
  - COMPILER="4.06.0"

os:
- linux
- osx

cache:
  apt: true
  directories:
  - ${HOME}/opam-cache

before_install:
    if [ $TRAVIS_OS_NAME = osx ]; then
    brew update; brew install --ignore-dependencies opam; fi

install:
- test -e ${HOME}/opam-cache/cache-${COMPILER}.tgz || scripts/opam-coq-init

script:
- curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh > install.sh
- echo | sudo sh install.sh
- set -o pipefail
- scripts/opam-coq-list-pr-files | xargs scripts/opam-coq-lint
- scripts/opam-coq-list-pr-files | xargs scripts/opam-coq-install-remove ${HOME}/opam-cache/cache-${COMPILER}.tgz
        
addons:
  apt:
    sources:
    - avsm
    packages:
    - aspcud
    - gcc-multilib
    - libgtksourceview2.0-dev

dist: trusty
sudo: required
matrix:
  fast_finish: true
  allow_failures:
  - os: osx
